pool:
  vmImage: 'ubuntu-20.04'

schedules:
- cron: "0 0 * * *"
  displayName: Daily Dependabot run

steps:

- script: |
    git clone https://github.com/dependabot/dependabot-script.git
  displayName: clone dependabot repo
  
- script: docker pull dependabot/dependabot-core
  displayName: pull dependabot-core Docker image

- script: |
    cd dependabot-script
    docker run -v "$(pwd):/home/dependabot/dependabot-script" \
               -w /home/dependabot/dependabot-script dependabot/dependabot-core bundle install \
               -j 3 \
               --path vendor
  displayName: install dependencies

- task: Bash@3
  inputs:
    filePath: 'scripts/dependabot-devops.sh'
  displayName: "run dependabot"